<?php
$nor=array(
"<h1>chacun son tour, quelqu'un cite une marque de voiture, la 1e lettre de chaque marque permet de faire l alphabet, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>chacun son tour, quelqu un cite un végétal, la 1e lettre de chaque marque permet de faire l alphabet, *N* commence.</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>dans ma valise, *N* commence</h1><br /><h3>4 gorgées pour celui qui se trompe</h3>",
"<h1>spécial : finissez tous vos verres si vous êtes en E105 ou E318</h1>",
"<h1>spécial : finissez la bouteille si vous êtes sur la pelouse</h1>",
"<h1>les noms de bière, *N* commence</h1>",
"<h1>à 3, désignez le plus alcoolique qui finira son verre</h1>",
"<h1>à 3, désignez le plus con qui finira son verre</h1>",
"<h1>la personne ayant les plus courts cheveux (miskin) distribue 3 gorgées</h1>",
"<h1>les 2 plus grands là, go boire 3 gorgées</h1>",
"<h1>designez tous ensemble le joueur le plus con qui prendra 4 gorgées</h1>",
"<h1>choisissez tous un joueur la suite arrive...</h1><br /><h3>le joueur désigné prend un cul sec et peut dessiner une bite sur le front du joueur de son choix</h3>",
"<h1>*N* prend 1 gorgee pour chaque bouton qu'il a sur la face</h1>",
"<h1>*N* prend 1 gorgee pour chaque fois qu'il a été en soiree ces 7 derniers jours</h1>",
"<h1>*N* distribue un cul sec ou *N* distribue 5 gorgees *N* choisi</h1>",
"<h1>Le premier a mettre une baffe a *N* distribue 4 gorgees</h1>",
"<h1>Le dernier a etre arrivé a la soiree distribue 3 gorgees</h1>",
"<h1>*N* prend une gorgee a chaque evenement jusqu'a ce que ton nom reapparaisse</h1>",
"<h1>Tournée générale si l'hôte a déja ralé ce soir</h1>",
"<h1>*N* bois autant de gorgees que de fois ou qqn est allé pisser depuis le debut de la soiree</h1>",
"<h1>Quand je dis DOO vous dites ?? Le premier à répondre distribue 3 gorgées</h1>",
"<h1>Quand je dis TOUJOURS PLUS ?? Vous dites ? et ? Les premiers à répondre distribuent 4 gorgées</h1>",
"<h1>Si t'as deja fais une soiree avec allain dont tu ne te rappelles plus bois 5 gorgees </h1>",
"<h1>Shi-Fu-Bois a tour de role avec votre voisin de droite</h1>",
"<h1>Les personnages de Bob l'eponge, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>Les avengers, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>Les habits/outils du beauf, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>*N* corvee de vaisselle pour toi et prend un cul sec pour la route (RIP si c'est chez grallain)</h1>",
"<h1>Si t'as déja gouté le calva de l'énorme *H*enrix et que t'es encore en vie, distribue 2 gorgées</h1>",
"<h1>*N*, raconte nous ton dernier plan cul</h1><br /><h3>*X* gorgées si les autres ne sont pas convaincus</h3>",
"<h1>*N* , *N* et *N* plan a 3! Vous etes maries et buvez le meme nombre de gorgees jusqu'a la fin du jeu</h1>",
"<h1>Bois autant de gorgées que tu as eu de rattrapages cette année</h1>",
"<h1>Si tu as un GPA superieur a 3 bois 5 gorgees sale intello</h1>",
"<h1>Si tu as un GPA inferieur a 3 bois 4 gorgees sale biz</h1>",
"<h1>Les filles si vous avez déjà pisser dehors buvez 4 gorgees</h1>",
"<h1>Les mecs si vous avez deja pisser dans un évier buvez 4 gorgées </h1>",
"<h1>Buvez autant de gorgees que de mecs dans la piece</h1>",
"<h1>Buvez autant de gorgees que de filles dans la piece</h1>",
"<h1>*N* avec l'accent russe tu parleras jusqu'a ce que tu sois a nouveau cité dans un evenement</h1>",
"<h1>les drogues, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>Si ton verre contient plus de la moitie de soft bois 5 gorgees </h1>",
"<h1>*N*, avoue quel surnom te donnaient tes parents, on devra t appeler ainsi pendant 3min, shot pour ceux qui se trompent</h1>",
"<h1>*N*, raconte une anecdote genante</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*G*, décidez d un surnom pour *N*, shot pour ceux qui se trompent</h1>",
"<h1>*G*, Limbo!</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*G* choisissez quelqu'un qui devra boire 2 gorgees dans chacun de vos verres</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*G* composez un cocktail dans lequel *N* devra dorenavant boire</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>Harry Potter ou Twilight</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>vaut mieux avoir : un corps de reve et une sale tete ou l'inverse</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>déplacer les objets par la pensée ou arreter le temps</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>apple ou android</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>coca ou pepsi ?</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>bk ou macdo ?</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>psg ou om ?</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>playstation ou xbox ?</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>baiser ton/ta partenaire ou te mettre une énorme mine ?</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>*N* echange de verre avec *N*</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>faire 300km à velo ou 50km en trotinette ?</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>sucer une bite quand tu dis une connerie ou te faire enculer quand tu dis un truc malin</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>etre aveugle ou etre sourd ?</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>mesurer 3m50 ou 1m ?</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>les synonymes d'argent, *N* commence (sauf si un trésorier est là)</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>savoir quand tu vas mourir ou savoir comment tu vas mourir ?</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>*N*, avec quel personne du *G* préférerais tu être en couple?</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>Les moyens de récupérer d'une cuite, *N* commence</h1>",
"<h1>*N*, désigne la personne la mieux habillée et la personne la plus mal habillée sans dire qui est qui</h1>",
"<h1>*N*, désigne la personne la plus débile et la personne la plus intelligente  sans dire qui est qui</h1>",
"<h1>*N*, désigne la personne la plus sobre et la personne la plus saoule sans dire qui est qui</h1>",
"<h1>*N*, désigne la personne la plus belle/sexy et la personne la plus vilaine sans dire qui est qui</h1>",
"<h1>Le premier à rapporter un objet violet</h1>",
"<h1>*N* choisis une syllabe, les autres doivent trouver un mot qui commence par cette syllabe, *N* commence</h1>",
"<h1>*N*, choisis un mot interdit, celui qui le prononce prend une gorgée</h1>",
"<h1>*N*, répète la dernière syllabe de chaque phrase pendant 3min</h1>",
"<h1>*N*, imite le poisson hors de l'eau</h1>",
"<h1>*N*, reconnais une personne de *G* à l'odeur</h1>",
"<h1>*N*, tu es polyglotte : le français t'est interdit pendant 2 minutes</h1>",
"<h1>Bataille de regard entre *N* et *N*</h1>",
"<h1>*N*, choisis une lettre, les autres doivent trouver des insultes commençant par cette lettre, *N* commence</h1>"
);
$deb=array(
"<h1>*N*, Mange un truc désigné par *N* sans les mains</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*N*, prend un rail de poivre sur le torse de *H*</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*G* scotchez votre verre a votre main pendant 30min</h1>",
"<h1>*G* scotchez vous un shot sur le menton et buvez le comme vous pouvez</h1>",
"<h1>*N*, scotche un shot sur le front de *N*, *N* doit le boire</h1>",
"<h1>*G* scotchez un shot sur votre biceps buvez le comme vous pouvez</h1>",
"<h1>Si t'en as pas plein la gueule ? Le premier à répondre fait une faciale avec un shot au joueur à sa gauche</h1>",
"<h1>Chabite ! *H* et *H*, le premier par terre bois 3 glous</h1>",
"<h1>*N* imite un lion pendant 10 longues secondes ou bois 3 gorgees</h1>",
"<h1>*N* imite un singe pendant 10 secondes ou bois 5 gorgees</h1>",
"<h1>le dernier a faire une olive a son voisin boit 4 gorgées</h1>",
"<h1>plutôt doom ou mheul ?</h1><br /><h3>vous êtes sacrément débile, cul sec général pour doomheul !</h3>",
"<h1>*N*, verse un peu de ton verre dans les mains de *N* et bois le</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*H* est très gay ! garde ta main sur la bite de *H* pendant 3 tours</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*N*, prends une bière bouteille, ouvre la et bois la cul sec sans les mains (demande @Enzo pour la technique)</h1><br /><h3>*X* gorgées si les autres ne sont pas convaincus</h3>",
"<h1>*N*, tourne 20 fois sur toi en 20 secondes et termine le verre d'un joueur</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*N* imite un phoque pendant 10 secondes ou bois 5 gorgees</h1><br /><h3>*X* gorgées si les autres ne sont pas convaincus</h3>",
"<h1>*N*, prend un baton puis fais 10 tours les plus rapides possibles, chaque tour oublié te vaudra un shot de pénalité</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>(*N*,*N*) et (*N*,*N*) font une course de poney sur le dos, la derniere equipe remplit et vide les verres de l autre équipe</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>le dernier a avoir rempli son verre peut le terminer</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>plutot envoyer ton partenaire a l'hosto chaque fois que vous faites l'amour ou avoir la diahree tous les jours </h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>fight entre *N* et *N*, le première a retirer une chaussette à l'autre distribue 1 shot</h1>",
"<h1>*N*, retire ton pantalon, tu ne peux le remettre qu'à deux conditions : sans les mains et en moins de 30 secondes</h1>",
"<h1>*N*, chante à la fenêtre</h1>",
"<h1>*N*, imite le ver de terre</h1>",
"<h1>*N* et *N*, échangez de pantalon</h1>"
);
$cen=array(
"<h1>les outils de la gdp, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>les amphis à centrale, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>cul sec si t'es BDL</h1>",
"<h1>distribue 2 gorgées si t'es un apo ou un minos</h1>",
"<h1>Les listes BDE, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>Les listes BDS, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>Les listes BDA, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>Le premier a ramener 4 ecocups de listes differentes distribue 5 gorgees </h1>",
"<h1>Les listeux boivent 3 gorgees</h1>",
"<h1>Buvez autant de gorgées que d'assos dans lesquelles vous etes</h1>",
"<h1>Parle en x0,5 comme Bachelet</h1><br /><h3>*X* gorgées si les autres ne sont pas convaincus</h3>",
"<h1>Les assos centraliennes, *N* commence</h1>",
"<h1>Les prez d'assos, *N* commence (ahahahahhahah) </h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>Bois autant de gorgees que de points que tu as donne aux ricos aux elections</h1>",
"<h1>Les membres de la liste Mac, *N* commence </h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>Bois autant de gorgees que de points que tu as donne aux illés aux elections</h1>",
"<h1>Si tu t'es déjà fait blacklist bois X gorgées </h1>",
"<h1>Bois autant de gorgees que tu as fait de torchos ces 6 derniers mois</h1>",
"<h1>*N* choisis une liste, *N* imite la mascotte de cette liste pendant une longue minute ou bois 5 gorgees</h1>",
"<h1>*G* faites le tour du bat f en courant le dernier arrivé prend un cul sec</h1>",
"<h1>*G* le dernier a monter dans la benne prend un cul sec (desole les nabots)</h1>",
"<h1>plutôt véronique le chibre ou bigland ?</h1><br /><h3>vous allez trop en cours, cul sec général !</h3>",
"<h1>*N*, si tu pense que les Apo c'est des PD bois 8 culs secs</h1>",
"<h1>*G* le premier a ramener un papier pour signaler un probleme dans son appart distribue 7 gorgees </h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>Plutot embrasser VLC ou se raser la tete, votez tous en meme temps</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>participer à hunger games ou inviter vlc en tete à tete</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>"
);
$cal=array(
"<h1>*N*, mime ta position préférée avec *N*</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*N*, lance un dé et enlève toi autant de vêtements</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*F*, lance un dé et enlève à *H* le nombre de vêtements indiqué</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*H*, lance un dé et enlève à *F* le nombre de vêtements indiqué</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*N*, lance un dé et enlève à *N* le nombre de vêtements indiqué</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*H* met le soutif de *F*</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*H* et *F* échangent leur haut</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>les objets de la cuisine utilisables pour le sexe, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>*N*, donne une fessee a *N*</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*N*, mange un glaçon sur le nombril de *N*</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*N*, prend un rail de poivre dans le décolleté de *F*</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*N*, prend un shot dans le décolleté de *F*</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*N*, quel est le dernier truc que tu aies achété dans un sex-shop ?</h1><br /><h3>*X* gorgées si les autres ne sont pas convaincus</h3>",
"<h1>*N*, combien de fois t'es tu masturbé cette semaine ? Bois autant de gorgées que de fois</h1>",
"<h1>as-tu déjà fait lamour sur ton lieu de travail ?</h1><br /><h3>Quel manque de respect ! Bois 3 gorgées si oui</h3>",
"<h1>as-tu déjà fait lamour dans un lieu public ?</h1><br /><h3>Quel manque de respect ! Bois 3 gorgées si oui</h3>",
"<h1>tes-tu masturbé aujourdhui ?</h1><br /><h3>Me serre pas la main ! Bois autant de shot que tu l'as fais aujourd'hui, branleur</h3>",
"<h1>les zones erogenes, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>as-tu déjà fait un plan à 3 ou plus ?</h1><br /><h3>Personne te croit, finis ton verre</h3>",
"<h1>quelle est ta position du Kamasutra préférée ?</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>as-tu déjà été attaché pendant que tu faisais l'amour ?</h1><br /><h3>Si oui, distribue 3 gorgées</h3>",
"<h1>les préliminaires, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>*N* nous fait un striptease ou fini son verre</h1>",
"<h1>*N* estime le nombre de rapports sexuels que *N* a eu ce denrnier mois, bois autant de gorgees que la difference</h1>",
"<h1>les excuses pour pas baiser, *N* commence</h1><br /><h3>Celui qui répète ou n'a plus d'idées bois *X* gorgées</h3>",
"<h1>*F*, prend une pièce dans tes lèvres (celles du haut), *H*, tu dois la récupérer avec ta bouche</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>si tu étais du sexe opposé pour une semaine, tu ferais quoi ? *N* commence</h1><br /><h3>Les minoriaires boivent 2 gorgées</h3>",
"<h1>*N*, avoue ton fantasme</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>Chaque personne du *G* note sur un papier qui a selon lui eu le + de partenaire sexuels, ceux qui ont eu juste distribuent des shots</h1>",
"<h1>*N*, avec qui dans *G* préférerais tu coucher?</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*F* et M s'isolent pendant 2 min</h1><br /><h3>*X* gorgées en cas de refus</h3>",
"<h1>*N*, twerke</h1>",
"<h1>*N*, twerke les pieds au mur</h1>",
"<h1>*N*, twerke les pieds sur les épaules de *N*</h1>",
"<h1>*N*, reçois une fessée par tous les autres joueurs</h1>",
"<h1>*N*, donne une fessée à tous les autres joueurs</h1>",
"<h1>*N*, Met une main aux fesses au 5 prochaines personnes qui utilisent ton prénom (même non joueur)</h1>",
"<h1>*N*, donne nous un cours sur le clito</h1>",
"<h1>*N*, donne nous un cours sur le point G</h1>",
"<h1>*N*, donne nous un cours sur la prostate</h1>",
"<h1>*N* et *N* font un 69</h1>"
);